# Project: vector
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = vector.o main.o
LINKOBJ  = vector.o main.o
LIBS     = -L"D:/Software/Dev C++/Installation/Dev-Cpp/MinGW64/lib" -L"D:/Software/Dev C++/Installation/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Software/Dev C++/Installation/Dev-Cpp/MinGW64/include" -I"D:/Software/Dev C++/Installation/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Software/Dev C++/Installation/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Software/Dev C++/Installation/Dev-Cpp/MinGW64/include" -I"D:/Software/Dev C++/Installation/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Software/Dev C++/Installation/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Software/Dev C++/Installation/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = vector.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

vector.o: vector.cpp
	$(CPP) -c vector.cpp -o vector.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
